---
apiVersion: v1
kind: ConfigMap
data:
  config: |
    [DEFAULT]
    LogLevel = DEBUG
    [DATABASE]
    Address = mysql
    Port = 3306
    Database = my_app
    User = root
    Password = root
    [VAULT]
    Enabled = False
metadata:
  name: config
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        # The consul-template container will pull secrets from Vault and expose
        # them as files on disk.
      - name: webapp
        image: kaparora/vault-demo-webapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: config
            mountPath: /usr/src/app/config
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: config
            path: config.ini
